// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDayM3MP5-Y8iBnKbWFwjpngyGJluQGBs',
    appId: '1:1011165073367:web:6cb92ae63d0743c361c592',
    messagingSenderId: '1011165073367',
    projectId: 'club-members-management-system',
    authDomain: 'club-members-management-system.firebaseapp.com',
    storageBucket: 'club-members-management-system.appspot.com',
    measurementId: 'G-0931LVCXKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfaJlFKnkc3Nh5ptPow_PtT6MafJgh6aE',
    appId: '1:1011165073367:android:a5e5a6ca3683829561c592',
    messagingSenderId: '1011165073367',
    projectId: 'club-members-management-system',
    storageBucket: 'club-members-management-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfePq5vPjl4Aq2zawJVzE9911fcKmaJrM',
    appId: '1:1011165073367:ios:b66c239919042f4e61c592',
    messagingSenderId: '1011165073367',
    projectId: 'club-members-management-system',
    storageBucket: 'club-members-management-system.appspot.com',
    iosBundleId: 'com.example.clubMembersManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfePq5vPjl4Aq2zawJVzE9911fcKmaJrM',
    appId: '1:1011165073367:ios:9499cd754558c4c361c592',
    messagingSenderId: '1011165073367',
    projectId: 'club-members-management-system',
    storageBucket: 'club-members-management-system.appspot.com',
    iosBundleId: 'com.example.clubMembersManagementSystem.RunnerTests',
  );
}
